version: 1.0.{build}

image:
- Visual Studio 2019

configuration:
- Debug
- Release

install:
- choco install opencppcoverage codecov
- set PATH=C:\Program Files\OpenCppCoverage;%PATH%

before_build:
- cmd:
    cmake -S . -B build -DBUILD_WITH_TEST=ON

build:
  project: build\illuminate.sln
  verbosity: normal

for:
-
  matrix:
    only:
    - configuration: Debug
  after_build:
  - cd build
  - OpenCppCoverage.exe --sources src --sources tests --export_type cobertura:coverage.xml --modules "*.exe" --cover_children -- %configuration%/illuminate.exe -C %configuration% --output-on-failure
  - codecov -f coverage.xml --root %APPVEYOR_BUILD_FOLDER%
