#ifndef ILLUMINATE_RESOURCE_SHADER_MATERIAL_DEFINES_H
#define ILLUMINATE_RESOURCE_SHADER_MATERIAL_DEFINES_H
#define OPACITY_TYPE_OPAQUE      0
#define OPACITY_TYPE_ALPHA_MASK  1
#define OPACITY_TYPE_TRANSPARENT 2
#ifndef OPACITY_TYPE
#define OPACITY_TYPE OPACITY_TYPE_OPAQUE
#endif
#endif
