#ifndef ILLUMINATE_RESOURCE_SHADER_MESH_DEFORM_DEFINES_H
#define ILLUMINATE_RESOURCE_SHADER_MESH_DEFORM_DEFINES_H
#define MESH_DEFORM_TYPE_STATIC  0
#define MESH_DEFORM_TYPE_SKELTON 1
#define MESH_DEFORM_TYPE_VAT     2
#ifndef MESH_DEFORM_TYPE
#define MESH_DEFORM_TYPE MESH_DEFORM_TYPE_STATIC
#endif
#endif
